name = "discord-dashboard-worker"
main = "src/index.ts"
compatibility_date = "2024-12-16"
account_id = "c400a4d044bf4655006c3245036fdb68"

compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
