// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

type CloudflareEnv = {
  DISCORD_PUBLIC_KEY: string;
  DISCORD_TOKEN: string;
	DISCORD_APPLICATION_ID: string;
};
