// Generated by Wrangler by running `wrangler types --experimental-include-runtime CloudflareEnv env.d.ts`

type CloudflareEnv = {
	ASSETS: Fetcher;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_TOKEN: string;
	DISCORD_APPLICATION_ID: string;
	DISCORD_GUILD_ID: string;
};
