name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-worker:
    name: Deploy Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: cd apps/worker
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "apps/worker"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            DISCORD_PUBLIC_KEY
            DISCORD_APPLICATION_ID
            DISCORD_TOKEN
            DISCORD_GUILD_ID
          environment: production
        env:
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}

  deploy-page:
    name: Deploy Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run build
        env:
          NEXT_PUBLIC_WORKER_URL: ${{ secrets.NEXT_PUBLIC_WORKER_URL }}
      - run: cd apps/page
      - name: Deploy Page
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "apps/page"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
